{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Connected to Python 3.13.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3761cb0-4593-4d26-a66d-85738a5240ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The secondary color is orange.\n",
      "The factorial of 7 is 5040.\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Prisca Muleka \n",
    "01/19/2025\n",
    "# Description: This program has two parts:\n",
    "# 1. Mixing primary colors to make secondary colors.\n",
    "# 2. Calculating the factorial of a number entered by the user.\n",
    "\"\"\"\n",
    "# 1 Mixing\n",
    "\n",
    "def mix_colors():\n",
    "    # Input: The user enters two primary colors.\n",
    "    # Process: The program checks if the colors are valid and finds the secondary color.\n",
    "    # Output: It shows the secondary color or an error message.\n",
    "\n",
    "    # Ask the user for two primary colors\n",
    "    color1 = input(\"Enter the first primary color (red, blue, yellow): \").lower()\n",
    "    color2 = input(\"Enter the second primary color (red, blue, yellow): \").lower()\n",
    "\n",
    "    # List of valid primary colors\n",
    "    valid_colors = [\"red\", \"blue\", \"yellow\"]\n",
    "\n",
    "    if color1 in valid_colors and color2 in valid_colors:\n",
    "        # Check for combinations of primary colors\n",
    "        if color1 == \"red\" and color2 == \"blue\":\n",
    "            print(\"The secondary color is purple.\")\n",
    "        elif color1 == \"red\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is orange.\")\n",
    "        elif color1 == \"blue\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is green.\")\n",
    "    else:\n",
    "        print(\"Error: Please enter only red, blue, or yellow.\")\n",
    "\n",
    "# 2 Calculate factorial\n",
    "\n",
    "def calculate_factorial():\n",
    "    # Input: The user enters a nonnegative integer.\n",
    "    # Process: The program checks if the number is valid and calculates the factorial using a loop.\n",
    "    # Output: It shows the factorial of the number.\n",
    "\n",
    "    # Ask the user for a number\n",
    "    num = int(input(\"Enter a nonnegative integer to calculate its factorial: \"))\n",
    "\n",
    "    if num < 0:\n",
    "        print(\"Error: Please enter a nonnegative integer.\")\n",
    "    else:\n",
    "        factorial = 1\n",
    "        for i in range(1, num + 1):\n",
    "            factorial *= i\n",
    "        print(f\"The factorial of {num} is {factorial}.\")\n",
    "\n",
    "# Calling the functions\n",
    "mix_colors()\n",
    "calculate_factorial()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c33b9db6-7923-4e72-a4ef-60d1779fe573",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The factorial of 9 is 362880.\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Prisca Muleka \n",
    "01/19/2025\n",
    "# Description: This program has two parts:\n",
    "# 1. Mixing primary colors to make secondary colors.\n",
    "# 2. Calculating the factorial of a number entered by the user.\n",
    "\"\"\"\n",
    "# 1 Mixing\n",
    "\n",
    "def mix_colors():\n",
    "    # Input: The user enters two primary colors.\n",
    "    # Process: The program checks if the colors are valid and finds the secondary color.\n",
    "    # Output: It shows the secondary color or an error message.\n",
    "\n",
    "    # Ask the user for two primary colors\n",
    "    color1 = input(\"Enter the first primary color (red, blue, yellow): \").lower()\n",
    "    color2 = input(\"Enter the second primary color (red, blue, yellow): \").lower()\n",
    "\n",
    "    # List of valid primary colors\n",
    "    valid_colors = [\"red\", \"blue\", \"yellow\"]\n",
    "\n",
    "    if color1 in valid_colors and color2 in valid_colors:\n",
    "        # Check for combinations of primary colors\n",
    "        if color1 == \"red\" and color2 == \"blue\":\n",
    "            print(\"The secondary color is purple.\")\n",
    "        elif color1 == \"red\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is orange.\")\n",
    "        elif color1 == \"blue\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is green.\")\n",
    "    else:\n",
    "        print(\"Error: Please enter only red, blue, or yellow.\")\n",
    "\n",
    "# 2 Calculate factorial\n",
    "\n",
    "def calculate_factorial():\n",
    "    # Input: The user enters a nonnegative integer.\n",
    "    # Process: The program checks if the number is valid and calculates the factorial using a loop.\n",
    "    # Output: It shows the factorial of the number.\n",
    "\n",
    "    # Ask the user for a number\n",
    "    num = int(input(\"Enter a nonnegative integer to calculate its factorial: \"))\n",
    "\n",
    "    if num < 0:\n",
    "        print(\"Error: Please enter a nonnegative integer.\")\n",
    "    else:\n",
    "        factorial = 1\n",
    "        for i in range(1, num + 1):\n",
    "            factorial *= i\n",
    "        print(f\"The factorial of {num} is {factorial}.\")\n",
    "\n",
    "# Calling the functions\n",
    "mix_colors()\n",
    "calculate_factorial()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d26090b5-44e9-46e8-8ed7-0e7a4310fc35",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The secondary color is purple.\n",
      "The factorial of 3 is 6.\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Prisca Muleka \n",
    "01/19/2025\n",
    "# Description: This program has two parts:\n",
    "# 1. Mixing primary colors to make secondary colors.\n",
    "# 2. Calculating the factorial of a number entered by the user.\n",
    "\"\"\"\n",
    "# 1 Mixing\n",
    "\n",
    "def mix_colors():\n",
    "    # Input: The user enters two primary colors.\n",
    "    # Process: The program checks if the colors are valid and finds the secondary color.\n",
    "    # Output: It shows the secondary color or an error message.\n",
    "\n",
    "    # Ask the user for two primary colors\n",
    "    color1 = input(\"Enter the first primary color (red, blue, yellow): \").lower()\n",
    "    color2 = input(\"Enter the second primary color (red, blue, yellow): \").lower()\n",
    "\n",
    "    # List of valid primary colors\n",
    "    valid_colors = [\"red\", \"blue\", \"yellow\"]\n",
    "\n",
    "    if color1 in valid_colors and color2 in valid_colors:\n",
    "        # Check for combinations of primary colors\n",
    "        if color1 == \"red\" and color2 == \"blue\":\n",
    "            print(\"The secondary color is purple.\")\n",
    "        elif color1 == \"red\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is orange.\")\n",
    "        elif color1 == \"blue\" and color2 == \"yellow\":\n",
    "            print(\"The secondary color is green.\")\n",
    "    else:\n",
    "        print(\"Error: Please enter only red, blue, or yellow.\")\n",
    "\n",
    "# 2 Calculate factorial\n",
    "\n",
    "def calculate_factorial():\n",
    "    # Input: The user enters a nonnegative integer.\n",
    "    # Process: The program checks if the number is valid and calculates the factorial using a loop.\n",
    "    # Output: It shows the factorial of the number.\n",
    "\n",
    "    # Ask the user for a number\n",
    "    num = int(input(\"Enter a nonnegative integer to calculate its factorial: \"))\n",
    "\n",
    "    if num < 0:\n",
    "        print(\"Error: Please enter a nonnegative integer.\")\n",
    "    else:\n",
    "        factorial = 1\n",
    "        for i in range(1, num + 1):\n",
    "            factorial *= i\n",
    "        print(f\"The factorial of {num} is {factorial}.\")\n",
    "\n",
    "# Calling the functions\n",
    "mix_colors()\n",
    "calculate_factorial()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
